### ISSUE TITLE
broken link not found

### ISSUE THREAD

**Issue by bqstony** [teggno/azure-pipelines-website-validator#1]
i have some broken link on my website. but it was not found.

this is my result

2020-09-16T09:37:57.9204347Z ##[section]Starting: Check preview.mbc-engineering.ch for broken links
2020-09-16T09:37:57.9212258Z ==============================================================================
2020-09-16T09:37:57.9212632Z Task         : Broken Link Checker
2020-09-16T09:37:57.9212995Z Description  : Test a web site for broken links.
2020-09-16T09:37:57.9213250Z Version      : 0.0.5
2020-09-16T09:37:57.9213486Z Author       : Christian Bär
2020-09-16T09:37:57.9214474Z Help         : Recursively test the pages of a web site for broken links. Provide a base URL and see the results in the build log.
2020-09-16T09:37:57.9215005Z ==============================================================================
2020-09-16T09:37:59.0251782Z (node:2432) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-16T09:37:59.0280391Z (node:2432) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-16T09:37:59.0281625Z (node:2432) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-16T09:37:59.0282251Z (node:2432) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-16T09:37:59.0282983Z (node:2432) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-09-16T09:37:59.0285324Z ##[section]Finishing: Check preview.mbc-engineering.ch for broken links

i expect somting like this:
![image](https://user-images.githubusercontent.com/10487253/93321408-68d34f00-f812-11ea-98fb-fdb3e39ae232.png)

this are my settings:

```
steps:
- task: teggno.website-validator.broken-link-checker.broken-link-checker@0
  displayName: 'Check preview.mbc-engineering.ch for broken links'
  inputs:
    baseurl: 'preview.mbc-engineering.ch'
    headOrGet: get
```
